### ISSUE TITLE
Português - Brasil

### ISSUE THREAD

**Issue by joaochris** [sws2apps/lmm-oa-sws#746]
Hello! Can you add Brazilian Portuguese, all types of translation?

**Comment by rhahao** [comment]
Hello @joaochris,

The [Portuguese, Brazilian](https://crowdin.com/project/cpe-lmmo/pt-BR) language has been added to Crowdin, and is now available for translation.

Thank you!

**Comment by joaochris** [comment]
@rhahao When will the language appear? 😁

![Screenshot_1](https://user-images.githubusercontent.com/76891864/216952707-b2e17981-f471-4a96-9d7b-d321c0b743df.png)

**Comment by rhahao** [comment]
Hi @joaochris,

Hopefully we will make it available today. We are working to update the [jw-epub-parser](https://github.com/sws2apps/jw-epub-parser) package to handle this new language, and it should be ready. We plan to have this translated on Crowdin as well in the future, in case you want to make a change on it.

Thanks!

**Comment by joaochris** [comment]
Thank you very much for your work, I'm really enjoying it!

**Comment by rhahao** [comment]
@joaochris, we noticed that epub is not available for this language on jw.org 😢

Therefore, please allow us just few more times to find and evaluate an applicable solution for you. Meanwhile, we can release it like this anyway, but you must enter the meeting workbook data manually for each week.

**Comment by joaochris** [comment]
@rhahao Yeah, unfortunately it was discontinued 😢. Okay, I'll be waiting. Thanks.

**Comment by joaochris** [comment]
Here in Brazil we use the format below, I need to put it like this in the translation into shortDatePickerFormat and shortDateTimeFormat? 

![Screenshot_3](https://user-images.githubusercontent.com/76891864/217110259-74fc2ee3-777f-4acf-a74e-fb0528f618c3.png)

**Comment by rhahao** [comment]
For `shortDatePickerFormat`, please use `dd/MM/yyyy`. For `shortDateTimeFormat`, please use `dd/mm/yyyy`.
These formats should output your desired format.

**Comment by joaochris** [comment]
@rhahao Will there be a way to automate the programming of the handout without the Epub? I will share with you what I currently need to do, maybe something will come in handy. Based on the video below, I copy all the website's programming and paste it into an automated google spreadsheet. Although this process is entirely manual, it is very quick to register every week.


https://user-images.githubusercontent.com/76891864/217252670-67be25e3-a92b-4127-b0f0-f697a6a6184d.mp4

**Comment by rhahao** [comment]
@joaochris thanks for sharing. I will try to see if this idea could be added as an alternate when importing data. But anyway, I just want to say that, I’ve finally managed to grab your source materials automatically now. I’m just finishing some automated testing before rolling it out. But it will be very soon!

**Comment by joaochris** [comment]
It's a programming genius 😅. I look forward to using it 😊.

**Comment by rhahao** [comment]
@joaochris, fyi: https://github.com/sws2apps/lmm-oa-sws/discussions/780

**Comment by joaochris** [comment]
@rhahao Some parts are still in English is that so?

![image](https://user-images.githubusercontent.com/76891864/217601361-e84ad090-1b17-40e1-a7cc-794b0610a063.png)

**Comment by rhahao** [comment]
Please go to the Congregation card and update your source materials language. Then import the source from jw.org.

**Comment by joaochris** [comment]
This error appeared: 

![image](https://user-images.githubusercontent.com/76891864/217602409-a07d219f-0545-4b0c-b0ae-ebd40953923a.png)
![image](https://user-images.githubusercontent.com/76891864/217602489-70c46b63-fc0c-4e3e-be8a-f310ec2d893a.png)

**Comment by rhahao** [comment]
Please allow me just to check one thing on the server part.

**Comment by rhahao** [comment]
😢 Sadly the method I used did not work well in the remote server we are currently using. I am very sorry for that. For now, I will display a message saying that this language is not supported when trying to import from jw.org. Probably I will go to build the method we discussed above.

**Comment by joaochris** [comment]
What a shame 😓. But no problem. I'm giving you a lot of work 😂. If there's a way to import with a few steps, like what we talked about, that's great 😄.

**Comment by joaochris** [comment]
But, in short, what method had you used to get the source material? I took a look at the codes, but I didn't understand it very well. Did you test it locally and it worked but not on the server?

**Comment by rhahao** [comment]
Yes, I actually fetch your mwb monthly page on jw.org, get the links to access all weekly schedules, and navigate to those pages After I get all of them that I start doing the parsing. But it seems like the server could not handle it until all these actions are done. I need to review it again somehow, may be there is a memory leak that I did not catch as well.

**Comment by joaochris** [comment]
I understood. But I believe you will make it 😁. See this bug, the names don't appear 😆

![Screenshot_21](https://user-images.githubusercontent.com/76891864/217618720-10747237-bc8e-4d61-bacb-b1f4ba15b88c.png)

**Comment by rhahao** [comment]
Is it always like this even if you re-open it again?

**Comment by joaochris** [comment]
From what I've seen, it's related to the language of the source material and forms. When I switched to English it worked. But in Portuguese it doesn't work.

![Screenshot_22](https://user-images.githubusercontent.com/76891864/217621569-bd9299dd-9351-4d89-8250-863691bd3f54.png)

**Comment by rhahao** [comment]
@joaochris: I believe the last issue you mentioned above was already solved, right?

**Comment by joaochris** [comment]
For sure! Thanks!
