### ISSUE TITLE
[FIX] Unable to import EPUB

### ISSUE THREAD

**Issue by joaochris** [sws2apps/lmm-oa-sws#760]
![image](https://user-images.githubusercontent.com/76891864/217366097-371bd113-6eb0-4e87-9b68-57b27198d26c.png)

![image](https://user-images.githubusercontent.com/76891864/217366123-7a337422-d398-4af5-80a8-2e717f7b3c7e.png)

It loads infinitely and this error appears in the console.

**Comment by rhahao** [comment]
Good catch @joaochris! I have to say that it’s been a long time that I did not use the method anymore. May be the bug was already sitting there for a very long time. 😂 I will add it to the list of items that need fix.
