### ISSUE TITLE
[FEAT] Indication when selected and not allowing to select the same chosen item

### ISSUE THREAD

**Issue by joaochris** [sws2apps/lmm-oa-sws#761]
It would be great if it indicated what was selected in the options and no longer allowed to choose the same item. Example, I chose "Prayer", then it would show an indication that it was selected, and then it would lock the item, since it was filled.

![Screenshot_8](https://user-images.githubusercontent.com/76891864/217374251-6c35c61e-7e20-4b4b-ba14-12fd71cb5d02.png)

**Comment by rhahao** [comment]
Hi @joaochris, actually the dropdown already has a soft highlight style applied to the selected item when you open (see the pic below):

![selection_highlighted](https://user-images.githubusercontent.com/26148770/217549927-6ae2fdb8-f097-46a4-876b-8346999586b8.png)

I will try to find if there is any way to adjust this dropdown item to make the current selection more noticeable.

Thanks!

**Comment by joaochris** [comment]
I think I didn't understand. In fact, my suggestion was for him to mark what was already selected, not the current selection. And block what was selected.

**Comment by rhahao** [comment]
Ah sorry! Now I understand it. 😁 I will add to the backlog list. Thanks

**Comment by joaochris** [comment]
@rhahao I had an idea that is related to this. I made an example to show one way that I see it could be more organized and easier to fill in the assignments.

Simply a square to mark the designations.

A notes field below.

And I think start date and end date could be merged into just one option with missing time.

And something that might make it easier too, would relate to the first section of student information. It would be like having checkboxes to mark if you are Publisher, Ministerial Servant and Elder.

So, (perhaps an option that can be checked in settings like "Default Assignments") where if enabled would automatically check the options that certain person as Publisher, Ministerial Servant or Elder can do. So we would have the job of just unchecking the ones he doesn't do at the moment.

![Designações](https://user-images.githubusercontent.com/76891864/218135623-0ae24c93-40d8-49ce-a6f3-4cbd99266cec.png)

**Comment by rhahao** [comment]
Thanks! I will take note of this.
The new Persons page will also take care of a person privilege, as you described.
