### ISSUE TITLE
[FEAT] Show the list of all registered people when entering "People"

### ISSUE THREAD

**Issue by joaochris** [sws2apps/lmm-oa-sws#765]
Is it possible as soon as I click on "People" it shows all registered people?

![Screenshot_13](https://user-images.githubusercontent.com/76891864/217390464-60d4b214-31d5-472d-86cb-416efb4f33d5.png)

**Comment by rhahao** [comment]
Thanks for this suggestion. We had this in the past, but due to some issues, we removed that option. I will try to see if it can be added back now.
