### ISSUE TITLE
[FEAT] Add Circuit Assembly to List 😁

### ISSUE THREAD

**Issue by joaochris** [sws2apps/lmm-oa-sws#767]
![Screenshot_15](https://user-images.githubusercontent.com/76891864/217394068-b305ab8e-b45d-4182-9a5f-9e155655b41b.png)

**Comment by rhahao** [comment]
Sure! I will add this request to our backlog list. (Originally, the idea would be to use the "Convention Week" for assembly as well but I see it could be confusing. Having separate entry for it sounds logical)
