### ISSUE TITLE
[FIX] Too many S-89 characters (Portuguese - Brazil)

### ISSUE THREAD

**Issue by joaochris** [sws2apps/lmm-oa-sws#781]
In that case, would I have to abbreviate the translation?

![Screenshot_23](https://user-images.githubusercontent.com/76891864/217628099-35d54e37-d210-4fd1-b4eb-716c5c509551.png)

**Comment by rhahao** [comment]
This text is taken from your mwb, so it would better to leave it as it as. But my question is: would it work for you if we just take the text after the dash separator?

**Comment by joaochris** [comment]
I didn't understand 😅

**Comment by rhahao** [comment]
This is how it looks like in English:

![Screenshot 2023-02-08 222058](https://user-images.githubusercontent.com/26148770/217630659-39627986-eaa2-44cc-8270-62c806be204f.png)

I guess for your language you make it clear directly on the meeting workbook which part the student should do. In some language, it’s always the same. Two return visits for example in English, but in the S-89 we added the text above.

**Comment by rhahao** [comment]
Another idea would be also to replace completely the text "Initial Call" or "Return Visit", and put in the correct text for the part, like: "Revisita — designação 1"

**Comment by joaochris** [comment]
But, in that case, would it have to be abbreviated? To leave it like this, for example:
![image](https://user-images.githubusercontent.com/76891864/217632765-7f7c86ea-edb2-4b83-9a59-a1a0208ffbca.png)

![image](https://user-images.githubusercontent.com/76891864/217632871-e7cd84e8-fe0d-466c-bcd6-ee599feac27f.png)

**Comment by joaochris** [comment]
In fact, you can leave it at that, because he already marks it as First Conversation in the square 😂. It makes no sense to repeat the word again below, just specify whether it is a 1 or 2 designation.
![image](https://user-images.githubusercontent.com/76891864/217633929-09fb5b09-150e-400d-9072-802c31ec412a.png)
![image](https://user-images.githubusercontent.com/76891864/217634079-a8272973-5a3a-4899-ae7e-ce09970dffc0.png)

**Comment by joaochris** [comment]
Do these two refer to the S-89?

![Screenshot_1](https://user-images.githubusercontent.com/76891864/217634759-4713a3d6-6c2f-4c3b-91e5-06f5e4faa32b.png)
![Screenshot_2](https://user-images.githubusercontent.com/76891864/217634785-24ccc5c3-6d6f-4852-8e75-0d19de715b1a.png)

**Comment by rhahao** [comment]
Yes, but they are also used when extracting the source materials (during my local testing of couse 😊) They need to match what is written on the meeting workbook.

**Comment by rhahao** [comment]
This is the text that we use for other languages:

![Screenshot 2023-02-08 224710](https://user-images.githubusercontent.com/26148770/217635736-2d4b3c6a-5951-401f-96a0-2fdef3197041.png)

**Comment by joaochris** [comment]
I understand now, sorry for my sluggishness. In English both parts have the same name. In Portuguese it already differentiates Designation 1 and Designation 2. So it's really enough to specify that.

**Comment by rhahao** [comment]
So I will update your language to be the same like the other languages then.

**Comment by joaochris** [comment]
Can you create the entries for Desgnação 1 and Designação 2 for the S89? I think it would be better that way. If this isn't interfering with the other languages.....

**Comment by joaochris** [comment]
Thank you, you are amazing!

**Comment by rhahao** [comment]
Hi @joaochris, hopefully the last update is solving this issue.
Thanks!
