### ISSUE TITLE
[FEAT] Alternate method for importing source materials if EPUB is not available

### ISSUE THREAD

**Issue by rhahao** [sws2apps/lmm-oa-sws#783]

**Comment by joaochris** [comment]
I had a crazy idea here, but I think the more ideas, the better for you to think about alternatives and see which fits best.

Lately I've been using Tampermonkey. It inserts scripts into the browser console. Kind of like that.

I thought of the idea, since you said you did all the steps on the server, how about running it locally?

In this case, the idea would be to insert a script in the console, first doing those steps you mentioned: "fetch your mwb monthly page on jw.org, get the links to access all weekly schedules, and navigate to those pages. After I get all of them that I start doing the parsing".

Then when I logged in to edit the source material, the script entered the information into the fields automatically. This crazy idea I had. I believe you want to do everything inside a server, because the purpose of your applications is to simplify our lives. But is there a way to do something similar like this inside the server? Would I need a function to fetch the entire schedule and then a button in source material to automatically fill in the fields according to weeks? Just some ideas :)

**Comment by rhahao** [comment]
Thanks for sharing! I will consider it. Also, I have updated the previous code for fetching the source, and I hope the time needed to execute will be reduced drastically. Let’s hope that it will succeed this time.

**Comment by joaochris** [comment]
These ideas of mine are more like if everything goes wrong in the end 😂😂

**Comment by rhahao** [comment]
Hi @joaochris, a new version has been released that should allow to import the schedules from JW.ORG. I’ve tested it also in production and it works fine. (I hope ... 😊) Some noisy CSP errors are appearing in the console right now, but I will fix it asap.

**Comment by rhahao** [comment]
The CSP error is now solved as well.

**Comment by joaochris** [comment]
@rhahao It works perfectly! I'm thrilled. Thank you from the heart. Congratulations on your effort and work. 😃

**Comment by joaochris** [comment]
@rhahao I found an error. He couldn't find the source material for this week's story.

![Screenshot_7](https://user-images.githubusercontent.com/76891864/218109270-d9ba9053-a818-4ae8-b3d8-d370532be680.png)

**Comment by rhahao** [comment]
Ah... ok thanks for sending the console error. Because I was not able to duplicate it on my end. It seems like it tries to find a person which no longer exists here. But I’m not really sure what happened, so I will adjust the code to catch this exception.

**Comment by joaochris** [comment]
person_displayName}else n[i.assignment]="",n[a]=""}return n.week_type=parseInt(t.week_type,10)||1,n.noMeeting=t.noMeeting||!1,n},is=async e=>{const n={...await Ez(e)};return n.week_type_name=await Ppe(n.week_type),n},gye=async e=>{const n={...await Ez(e)};return n.week_type_name=await Ape(n.week_type),n},vye=async e=>{const t=+e.split("/")[0],n=+e.split("/")[1];let r;const o=await ot.sws_pocket.where("[month+year]").equals([t,n]).first();o?r=o.id:(r=window.crypto.randomUUID(),await ot.sws_pocket.add({id:r,month:t,year:n}));let i=[],a=[];const s=await iv(e);for(let c=0;c<s.length;c++){const u=s[c].value,p=await gye(u),d=await Tpe(u);i.push({...p}),a.push({...d})}return{sources:a,id:r,schedules:i,month:t,year:n}},Yd=async(e,t,n)=>{const r={};r[e]=t,await ot.table("sched_MM").update(n,{...r})},yye=async e=>{let t=0,n=0;const r=await bn(tv),o=await is(e),i=await Gl(e);if(o.noMeeting)return{total:0,assigned:0};t=t+1,o.week_type===1&&r>1&&(t=t+1),o.chairmanMM_A&&o.chairmanMM_A!==""&&(n=n+1),o.chairmanMM_B&&o.chairmanMM_B!==""&&(n=n+1),t=t+1,o.opening_prayer&&o.opening_prayer!==""&&(n=n+1),t=t+1,o.tgw_talk&&o.tgw_talk!==""&&(n=n+1),t=t+1,o.tgw_gems&&o.tgw_gems!==""&&(n=n+1),t=t+1,o.week_type===1&&r>1&&(t=t+1),o.bRead_stu_A&&o.bRead_stu_A!==""&&(n=n+1),o.bRead_stu_B&&o.bRead_stu_B!==""&&(n=n+1);for(let s=1;s<=4;s++){const l=`ass${s}_type`,c=i[l];(c===101||c===102||c===103||c===108||c>=140&&c<170||c>=170&&c<200)&&(t=t+2,o.week_type===1&&r>1&&(t=t+2)),c===104&&(t=t+1,o.week_type===1&&r>1&&(t=t+1));const u=`ass${s}_stu_A`,p=`ass${s}_ass_A`,d=`ass${s}_stu_B`,f=`ass${s}_ass_B`;o[u]&&o[u]!==""&&(n=n+1),o[p]&&o[p]!==""&&(n=n+1),o[d]&&o[d]!==""&&(n=n+1),o[f]&&o[f]!==""&&(n=n+1)}t=t+1,o.lc_part1&&o.lc_part1!==""&&(n=n+1);let a=!1;return i.lcCount_override===void 0&&i.lcCount===2&&(a=!0),i.lcCount_override!==void 0&&i.lcCount_override===2&&(a=!0),a&&(t=t+1,o.lc_part2&&o.lc_part2!==""&&(n=n+1)),o.week_type===1&&(t=t+1,o.cbs_conductor&&o.cbs_conductor!==""&&(n=n+1),t=t+1,o.cbs_reader&&o.cbs_reader!==""&&(n=n+1)),t=t+1,o.closing_prayer&&o.closing_prayer!==""&&(n=n+1),{total:t,assigned:n}},bye=async()=>{const{t:e}=zt(),t=await bn(LR),n=await bn(IA),r=new Date().getFullYear(),o=new Date().getMonth(),i={label:e("selectAll",{ns:"ui"}),value:"sched",children:[]};for await(const a of t){const s=+a.value;if(s>=r){const l={};l.value=a.value,l.label=a.label,l.children=[],(await Mpe(a.value)).forEach(u=>{const p=parseInt(u.value.split("/")[0],10)-1;let d=!0;if(s===r&&p<o&&(d=!1),d){const f=`${n[p]} ${u.value.split("/")[1]}`;l.children.push({label:f,value:u.value})}}),i.children.push(l)}}return i},wye=e=>e.filter(n=>n.indexOf("/")>=0)||[],n7e=async e=>{const t=await bn(s_),n=await iv(e),r=[];return n.forEach(o=>{const i=o.weekOf,a=i.split("/")[1],s=i.split("/")[0],l=i.split("/")[2],c=new Date(l,+s-1,a),u=Or(c,t);r.push({value:o.value,label:u})}),r},Nz=async(e,t,n)=>{const r=[];if(e){let a=await iv(t.value);for(let s=0;s<a.length;s++){const l={};l.value=a[s].weekOf,r.push(l)}}else r.push({value:n.value});let o=0,i=0;for await(const a of r){const s=a.value,{total:l,assigned:c}=await yye(s);o+=l,i+=c}return{weeks:r,total:o,assigned:i}},xye=async()=>{const e=[];let t={};const n=await ot.table("assignment").reverse().reverse().sortBy("code");for(let r=0;r<n.length;r++)t={},t.code=n[r].code,t.assignable=n[r].assignable,t.assignment_type_name=n[r].assignment_type_name,t.maleOnly=n[r].maleOnly||!1,t.type=n[r].type,t.linkTo=n[r].linkTo,e.push(t);return e},Kt=async(e,t,n)=>{const r=await ot.table("sched_MM").get({weekOf:e}),o=r[n],i=r.changes?[...r.changes]:[],a={};a[n]=t;const s=i.findIndex(u=>u.field===n);s!==-1&&i.splice(s,1),i.push({date:new Date().toISOString(),field:n,value:t}),a.changes=i,await ot.table("sched_MM").update(e,{...a});const l=await sv();await sn(fs,l),await Tye(o,t);const c=await bn(Qg);if(t===c){const u=await bn(Kb);await sn(Kb,!u)}},sv=async()=>{try{const e=await ot.table("sched_MM").toArray(),t=(await ot.persons.toArray()).length;let n=[];if(t>0){let r=0;for(let o=0;o<e.length;o++){let i={};const a=await Gl(e[o].weekOf),[s,l,c]=e[o].weekOf.split("/"),u=new Date(c,s-1,l),p=await bn(s_),d=Or(u,p),f=[],m=["weekOf","week_type","noMeeting","isReleased","changes"];for(const[h,b]of Object.entries(e[o]))m.indexOf(h)===-1&&b&&b!==""&&f.push({assignment:h,person:b});for await(const h of f){i.ID=r,i.weekOf=e[o].weekOf,i.weekOfFormatted=d,i.studentID=h.person;const b=await qR(h.person);if(i.studentName=b?.person_displayName||"",i.class="",h.assignment==="chairmanMM_A"&&(i.assignmentID=110,i.assignmentName=zt().t("chairmanMidweekMeeting2",{ns:"ui"})),h.assignment==="chairmanMM_B"&&(i.assignmentID=110,i.assignmentName=zt().t("auxClassCounselor",{ns:"ui"})),h.assignment==="opening_prayer"&&(i.assignmentID=111,i.assignmentName=zt().t("openingPrayer",{ns:"ui"})),h.assignment==="tgw_talk"&&(i.assignmentID=112,i.assignmentName=zt().t("tgwTalk",{ns:"ui"}),i.assignmentSource=a.tgwTalk_src),h.assignment==="tgw_gems"&&(i.assignmentID=113,i.assignmentName=zt().t("tgwGems",{ns:"ui"})),h.assignment.startsWith("bRead_stu_")){const v=h.assignment.split("_")[2];i.assignmentID=100,i.assignmentName=zt().t("bibleReading",{ns:"ui"}),i.class=v,i.studyPoint=a.bibleReading_study}if(h.assignment.startsWith("ass")&&h.assignment.includes("_stu_")){const v=h.assignment.split("_")[2],g=h.assignment.split("_")[0]+"_type",y=h.assignment.split("_")[0]+"_study",w=a[g],x=a[y];i.assignmentID=w,w===101||w>=140&&w<170?i.assignmentName=zt().t("initialCall",{ns:"ui"}):w===102||w>=170&&w<200?i.assignmentName=zt().t("returnVisit",{ns:"ui"}):w===103?i.assignmentName=zt().t("bibleStudy",{ns:"ui"}):w===104?i.assignmentName=zt().t("talk",{ns:"ui"}):w===108&&(i.assignmentName=zt().t("memorialInvite",{ns:"ui"})),i.class=v,i.studyPoint=x}if(h.assignment.startsWith("ass")&&h.assignment.includes("_ass_")){const v=h.assignment.split("_")[2];i.assignmentID=109,i.assignmentName=zt().t("assistant",{ns:"ui"}),i.class=v}if(h.assignment.startsWith("lc_part")){const v=h.assignment.slice(-1),g=`lcPart${v}_src`,y=`lcPart${v}_time`,w=`lcPart${v}_content`;i.assignmentID=114,i.assignmentName=zt().t("lcPart",{ns:"ui"}),i.assignmentSource=`(${a[y]} min.) ${a[g]}`,i.assignmentContent=a[w]}h.assignment==="cbs_conductor"&&(i.assignmentID=115,i.assignmentName=zt().t("cbsConductor",{ns:"ui"}),i.assignmentSource=a.cbs_src),h.assignment==="cbs_reader"&&(i.assignmentID=116,i.assignmentName=zt().t("cbsReader",{ns:"ui"}),i.assignmentSource=a.cbs_src),h.assignment==="closing_prayer"&&(i.assignmentID=111,i.assignmentName=zt().t("closingPrayer",{ns:"ui"})),n.push(i),i={},r++}}n.sort((o,i)=>{const a=o.weekOf.split("/")[2]+"/"+o.weekOf.split("/")[0]+"/"+o.weekOf.split("/")[1],s=i.weekOf.split("/")[2]+"/"+i.weekOf.split("/")[0]+"/"+i.weekOf.split("/")[1];return a<s?1:-1})}return n}catch{}},_ye=async e=>(await sv()).filter(r=>r.studentID===e),Sye=async e=>{const n=(await bn(fs)).filter(o=>o.assignmentID===100&o.studentID===e);let r;return n.length>0&&(r=n[n.length-1].weekOf),r},Cye=async e=>{const n=(await bn(fs)).filter(o=>o.assignmentID===101&o.studentID===e);let r;return n.length>0&&(r=n[n.length-1].weekOf),r},kye=async e=>{const n=(await bn(fs)).filter(o=>o.assignmentID===102&o.studentID===e);let r;return n.length>0&&(r=n[n.length-1].weekOf),r},Pye=async e=>{const n=(await bn(fs)).filter(o=>o.assignmentID===103&o.studentID===e);let r;return n.length>0&&(r=n[n.length-1].weekOf),r},Aye=async e=>{const n=(await bn(fs)).filter(o=>o.assignmentID===104&o.studentID===e);let r;return n.length>0&&(r=n[n.length-1].weekOf),r},Rye=async e=>{const n=(await bn(fs)).filter(o=>o.studentID===e);let r;return n.length>0&&(r=n[0].weekOf),r},Tye=async(e,t)=>{let n;for(let r=1;r<=2;r++)if(r===1?n=e:n=t,n){const o=await Sw(n);if(o){const i=await Rye(n),a={};a.lastAssignment=i,a.changes=o.changes||[];const s=a.changes.findIndex(u=>u.field==="lastAssignment");s!==-1&&a.changes.splice(s,1),a.changes.push({date:new Date().toISOString(),field:"lastAssignment",value:i}),await ot.table("persons").update(o.id,{...a});const l=await HR();await sn(Yl,l),await sn(zR,l);const c=await sv();await sn(fs,c)}}},r7e=async e=>{const t=await bn(Ta),n=[],r=await iv(e);for(let i=0;i<r.length;i++){const a=r[i].value,s=await is(a);if(!s.noMeeting){const l={};l.value=a;const c=new Date(a),u=Or(c,zt().t("shortDateFormat",{ns:"ui"}));l.label=u,l.children=[];const p=await Gl(a);let d={},f={};(s.bRead_stu_A&&s.bRead_stu_A!==""||s.bRead_stu_B&&s.bRead_stu_B!=="")&&(f.label=zt().t("bibleReading",{ns:"ui",lng:t}),f.value=a+"-0@bRead",f.children=[],s.bRead_stu_A&&s.bRead_stu_A!==""&&(d={},d.value=a+"-0@bRead-A",d.label=zt().t("mainHall",{ns:"ui",lng:t}),f.children.push(d)),s.bRead_stu_B&&s.bRead_stu_B!==""&&(d={},d.value=a+"-0@bRead-B",d.label=zt().t("auxClass1",{ns:"ui",lng:t}),f.children.push(d)),l.children.push(f));const m=await bn(tz);for(let h=1;h<=4;h++){const b="ass"+h+"_stu_A",v="ass"+h+"_stu_B",g="ass"+h+"_type";if(s[b]&&s[b]!==""||s[v]&&s[v]!==""){f={};let y;y=m.findIndex(w=>w.value===p[g]),f.label=y>=0?m[y].label:"",f.value=a+"-"+h+"@ass"+h,s[b]&&s[b]!==""&&(f.children=[],d={},d.value=a+"-"+h+"@ass"+h+"-A",d.label=zt().t("mainHall",{ns:"ui",lng:t}),f.children.push(d)),s[v]&&s[v]!==""&&(f.children=[],d={},d.value=a+"-"+h+"@ass"+h+"-B",d.label=zt().t("auxClass1",{ns:"ui",lng:t}),f.children.push(d)),l.children.push(f)}}l.children.length>0&&n.push(l)}}const o={};return o.value="S89",o.label=zt().t("allWeeks",{ns:"ui"}),o.children=n,o},o7e=async(e,t,n)=>{const r=await bn(Ta);let o="",i="",a=0;t==="bRead"?o="bRead_stu_"+n:t==="ass1"?(o="ass1_stu_"+n,i="ass1_ass_"+n,a="ass1_type"):t==="ass2"?(o="ass2_stu_"+n,i="ass2_ass_"+n,a="ass2_type"):t==="ass3"?(o="ass3_stu_"+n,i="ass3_ass_"+n,a="ass3_type"):t==="ass4"&&(o="ass4_stu_"+n,i="ass4_ass_"+n,a="ass4_type");const s=await ea();let l=parseInt(s.meeting_day,10);const[c,u,p]=e.split("/");l=parseInt(u,10)+l-1;const d=new Date(p,c-1,l),f=Or(d,zt().getDataByLanguage(r).ui.shortDateFormat),m=await Gl(e),h=await is(e),b={},v=h[o],{person_name:g}=await Sw(v);if(b.studentName=g,b.assistantName="",b.isBRead=!1,b.isInitialCall=!1,b.initialCallSpec="",b.isReturnVisit=!1,b.returnVisitSpec="",b.isBibleStudy=!1,b.bibleStudySpec="",b.isTalk=!1,b.assignmentDate=f,b.isMemorialInvite=!1,t==="ass1"||t==="ass2"||t==="ass3"||t==="ass4"){let y=m[a];if(y>=140&&y<170&&(y=101),y>=170&&y<200&&(y=102),y===101||y===102||y===103||y===108){const T=h[i];if(typeof T<"u"&&T!==""){const O=await Sw(T);b.assistantName=O.person_name}}let w=m.ass1_type;w>=140&&w<170&&(w=101),w>=170&&w<200&&(w=102);let x=m.ass2_type;x>=140&&x<170&&(x=101),x>=170&&x<200&&(x=102);let S=m.ass3_type;S>=140&&S<170&&(S=101),S>=170&&S<200&&(S=102);let C=m.ass4_type;if(C>=140&&C<170&&(C=101),C>=170&&C<200&&(C=102),y===101||y===108||y===102){y===101&&(b.isInitialCall=!0),y===108&&(b.isMemorialInvite=!0),y===102&&(b.isReturnVisit=!0);let T="initialCallSpec";y===102&&(T="returnVisitSpec"),t==="ass1"?w===x&&(b[T]=zt().t("s89Part1Label",{lng:r,ns:"source"})):t==="ass2"?(x===w&&(b[T]=zt().t("s89Part2Label",{lng:r,ns:"source"})),x===S&&(b[T]=zt().t("s89Part1Label",{lng:r,ns:"source"}))):t==="ass3"?(S===x&&(b[T]=zt().t("s89Part2Label",{lng:r,ns:"source"})),S===C&&(b[T]=zt().t("s89Part1Label",{lng:r,ns:"source"}))):t==="ass4"&&C===S&&(b[T]=zt().t("s89Part2Label",{lng:r,ns:"source"}))}else y===103?b.isBibleStudy=!0:y===104&&(b.isTalk=!0)}else b.isBRead=!0;return n==="A"?(b.isMainHall=!0,b.isAuxClass=!1):(b.isMainHall=!1,b.isAuxClass=!0),b},i7e=async e=>{const t=[],n=await iv(e),r=Or(await bn(vR),"h:MM");for(let o=0;o<n.length;o++){const i=n[o].value,a=await is(i),s=await Gl(i),l={};l.pgmStart=r,l.openingComments=dr(l.pgmStart,5),l.tgwTalk=dr(l.openingComments,1),l.tgwGems=dr(l.tgwTalk,10),l.bibleReading=dr(l.tgwGems,10),l.ayf1=dr(l.bibleReading,5),s.ass1_type===105||s.ass1_type===106||s.ass1_type===107||s.ass1_type===117?l.ayf2=dr(l.ayf1,+s.ass1_time):l.ayf2=dr(l.ayf1,+s.ass1_time+1),s.ass2_type===105||s.ass2_type===106||s.ass2_type===107||s.ass2_type===117?l.ayf3=dr(l.ayf2,+s.ass2_time):l.ayf3=dr(l.ayf2,+s.ass2_time+1),s.ass3_type===105||s.ass3_type===106||s.ass3_type===107||s.ass2_type===117?l.ayf4=dr(l.ayf3,+s.ass3_time):l.ayf4=dr(l.ayf3,+s.ass3_time+1),s.ass4_time!==""?s.ass4_type===105||s.ass4_type===106||s.ass4_type===107||s.ass2_type===117?l.middleSong=dr(l.ayf4,+s.ass4_time):l.middleSong=dr(l.ayf4,+s.ass4_time+1):l.middleSong=l.ayf4,l.lc1=dr(l.middleSong,5),s.lcPart1_time_override?l.lc2=dr(l.lc1,s.lcPart1_time_override):l.lc2=dr(l.lc1,s.lcPart1_time),a.week_type===1?(s.lcCount_override&&(s.lcCount_override===1?l.cbs=l.lc2:l.cbs=dr(l.lc2,s.lcPart2_time_override)),s.lcCount_override===void 0&&(s.lcCount===1?l.cbs=l.lc2:l.cbs=dr(l.lc2,s.lcPart2_time)),s.cbs_time_override?l.concludingComments=dr(l.cbs,s.cbs_time_override):l.concludingComments=dr(l.cbs,30),l.pgmEnd=dr(l.concludingComments,3)):(s.lcCount===1?l.concludingComments=l.lc2:s.lcPart2_time_override?l.concludingComments=dr(l.lc2,s.lcPart2_time_override):l.concludingComments=dr(l.lc2,s.lcPart2_time),l.coTalk=dr(l.concludingComments,3),l.pgmEnd=dr(l.coTalk,30));const c={};c.week=i,c.scheduleData=a,c.sourceData={...s,...l},t.push(c)}return t},dr=(e,t)=>{const n=e.split(":"),r=+n[0],o=+n[1];let i=r,a=o+t;return a>=60&&(i=r+1,a=a-60),`${i}:${a<10?`0${a}`:a}`},Oye=async()=>{try{const e=await ot.table("sched_MM").toArray(),t=[];for await(const f of e){const m=f.weekOf,h=await is(m),b=await Gl(m);t.push({...h,...b})}const n=await bn(IA);let{local_uid:r,pocket_members:o}=await ea();o=o||[];const i=new Date,a=new Date(i.getFullYear(),i.getMonth(),i.getDate()),s=a.getDay(),l=a.getDate()-s+(s===0?-6:1),c=new Date(a.setDate(l)),u=24*60*60*1e3,p=["chairmanMM_A","chairmanMM_B","opening_prayer","tgw_talk","tgw_gems","bRead_stu_A","bRead_stu_B","ass1_stu_A","ass1_ass_A","ass1_stu_B","ass1_ass_B","ass2_stu_A","ass2_ass_A","ass2_stu_B","ass2_ass_B","ass3_stu_A","ass3_ass_A","ass3_stu_B","ass3_ass_B","ass4_stu_A","ass4_ass_A","ass4_stu_B","ass4_ass_B","lc_part1","lc_part2","cbs_conductor","cbs_reader","closing_prayer"],d=[];return t.forEach(f=>{const m=new Date(f.weekOf);Math.round((m-c)/u)>=0&&p.forEach(b=>{const v=`${b}_dispName`,g=f[b],y=f[v];let w=!1,x=!1;if(g===r&&(w=!0),o.some(S=>S.person_uid===g)&&(w=!0,x=!0),w){const S=f.weekOf.split("/"),C=+S[0]-1,T=`${n[C]} ${S[2]}`,O={};if(O.month_value=T,O.id=window.crypto.randomUUID(),O.weekOf=f.weekOf,O.person=g,O.personDispName=y,b==="chairmanMM_A"&&(O.assignmentName=zt().t("chairmanMidweekMeeting2",{ns:"ui"})),b==="chairmanMM_B"&&(O.assignmentName=zt().t("auxClassCounselor",{ns:"ui"})),b==="opening_prayer"&&(O.assignmentName=zt().t("openingPrayerMidweekMeeting",{ns:"ui"})),b==="tgw_talk"&&(O.assignmentName=zt().t("tgwTalk2",{ns:"ui"}),O.assignmentSource=f.tgwTalk_src),b==="tgw_gems"&&(O.assignmentName=zt().t("tgwGems2",{ns:"ui"})),b.startsWith("bRead_stu_")){const k=b.split("_")[2];O.assignmentName=zt().t("bibleReading",{ns:"ui"}),O.class=k,O.studyPoint=f.bibleReading_study,O.assignmentSource=f.bibleReading_src}if(b.startsWith("ass")&&b.includes("_stu_")){const k=b.split("_")[2],A=b.split("_")[0]+"_type",R=b.split("_")[0]+"_study",M=b.split("_")[0]+"_time",P=b.split("_")[0]+"_src",V=`${b.replace("_stu_","_ass_")}_dispName`,Q=f[A],W=f[R],Y=f[P],ee=f[M],H=f[V];O.assignmentName=`${yL(Q)} - ${zt().t("student",{ns:"ui"})}`,O.assistantDispName=H,O.assignmentTime=ee,O.assignmentSource=Y,O.assignmentType="ayf",O.class=k,O.studyPoint=W}if(b.startsWith("ass")&&b.includes("_ass_")){const k=b.split("_")[2],A=b.split("_")[0]+"_study",R=b.split("_")[0]+"_type",M=b.split("_")[0]+"_src",P=b.split("_")[0]+"_time",V=`${b.replace("_ass_","_stu_")}_dispName`,Q=f[A],W=f[M],Y=f[P],ee=f[V],H=f[R];O.assignmentName=`${yL(H)} - ${zt().t("assistant",{ns:"ui"})}`,O.studentForAssistant=ee,O.assignmentTime=Y,O.assignmentSource=W,O.assignmentType="ayf",O.class=k,O.studyPoint=Q}if(b.startsWith("lc_part")){const k=b.slice(-1),A=`lcPart${k}_src`,R=`lcPart${k}_time`,M=`lcPart${k}_content`;O.assignmentName=zt().t("lcPart",{ns:"ui"}),O.assignmentTime=f[R],O.assignmentSource=f[A],O.assignmentContent=f[M]}b==="cbs_conductor"&&(O.assignmentName=zt().t("cbsConductor2",{ns:"ui"}),O.assignmentSource=f.cbs_src),b==="cbs_reader"&&(O.assignmentName=zt().t("cbsReader2",{ns:"ui"}),O.assignmentSource=f.cbs_src),b==="closing_prayer"&&(O.assignmentName=zt().t("closingPrayerMidweekMeeting",{ns:"ui"})),O.isBehalf=x,d.push(O)}})}),d.sort((f,m)=>{const h=f.weekOf.split("/")[2]+"/"+f.weekOf.split("/")[0]+"/"+f.weekOf.split("/")[1],b=m.weekOf.split("/")[2]+"/"+m.weekOf.split("/")[0]+"/"+m.weekOf.split("/")[1];return h>b?1:-1}),d}catch(e){console.log(e)}};/*! *****************************************************************************

**Comment by rhahao** [comment]
A new version has been released to handle the above error. Thank you!

**Comment by joaochris** [comment]
Thanks for the correction :)
