### ISSUE TITLE
[Enhancement Idea] Parts of Living As Christians with the amount of minutes after the source of matter

### ISSUE THREAD

**Issue by joaochris** [sws2apps/lmm-oa-sws#790]
I saw that when exporting the schedule the minutes appear later. If possible, also put it here to create a pattern :).

![Screenshot_1](https://user-images.githubusercontent.com/76891864/217670058-e7230f11-2a2d-4f64-826d-79dd942f8333.png)

**Comment by rhahao** [comment]
Sure thing! We will update it as suggested. Thanks.
