### ISSUE TITLE
[Enhancement Idea] Visit of Circuit Overseer

### ISSUE THREAD

**Issue by joaochris** [sws2apps/lmm-oa-sws#793]
When defining for this type of meeting, it would be interesting if a field appeared for us to enter the name of the CO and the subject of his talk, blocking the talk automatically at 30min. This would hide the Congregation Bible Study field and show this one. Instead of when exporting the programming it just appears (Talk given by Circuit Overseer).

Also, you could leave the final song blank, as it will be chosen by the CO. I also noticed that there is some bug, that the final song doesn't appear in the programming:

![Screenshot_6](https://user-images.githubusercontent.com/76891864/217686969-8fca82d7-3935-4f73-a653-2c8984ba575b.png)

**Comment by rhahao** [comment]
Hello @joaochris, thanks as always for your contribution. I personally really appreciate it.

On this one, I will add to the backlog list the first part. Regarding the concluding song, here it is on purpose that only the text song is appearing when CO visit. Currently, we hide the song number as we will song chosen by CO as you said. Do you believe that it would better to remove this text completely?

**Comment by joaochris** [comment]
I understood. Thank you. If possible, could you leave it as I said, not hide the song from the S-140 programming, only when editing the source material, leave the final song blank so we can select the CO song, and after filling it, this song will appear in schedule S-140 when exporting. Did you get it?

**Comment by rhahao** [comment]
Yeah sure. I will add to the backlog list. Thank you!

**Comment by rhahao** [comment]
Hi @joaochris, this is how I’ve adjusted the S-140 form:

![Screenshot 2023-02-12 230602](https://user-images.githubusercontent.com/26148770/218334426-1d58730c-d9c3-4679-bcae-c170ec87f717.png)

A text field has been added to the Source Material editing page to allow you to enter the CO talk title. Also the concluding song from jw.org will be hidden but it will be replaced by the new one that you will be choosing. These will only display when you choose the CO visit week type.

![Screenshot 2023-02-12 230946](https://user-images.githubusercontent.com/26148770/218334643-0de6a0a2-cab2-48b6-abcc-31a45c1dd5f2.png)

Do you have any additional comments before I finalize it?

Thanks!

**Comment by joaochris** [comment]
Great! Is it possible to add a field to put his name?

**Comment by rhahao** [comment]
Ok thanks! I will add a field for that in the Congregation Settings page.
