### ISSUE TITLE
[FIX] Error when assigning the second person to an Auxiliary classroom

### ISSUE THREAD

**Issue by joaochris** [sws2apps/lmm-oa-sws#805]
![Animação](https://user-images.githubusercontent.com/76891864/218265739-1e41db61-12bc-4149-8d86-a4dbdbd2c165.gif)

![Screenshot_9](https://user-images.githubusercontent.com/76891864/218265974-5182b50d-81ab-4c35-a6cb-23d945dfdf41.png)

![image](https://user-images.githubusercontent.com/76891864/218266023-234e0802-886b-4e97-bb34-5bb2e7a9f9cb.png)

**Comment by rhahao** [comment]
Thanks for the report. I will take a look at it. It seems like they are assigned but the apps failed to display them. (The error below is normal though ☺️ It's just a 403 error indicating that your user session has ended, and you need to re-authenticate to use online features again)

**Comment by rhahao** [comment]
Hello @joaochris, I was not able to duplicate the above issue. Does it happen for every week or just for a specific one?

**Comment by joaochris** [comment]
The error has been fixed :)
