### ISSUE TITLE
Class count

### ISSUE THREAD

**Issue by joaochris** [sws2apps/lmm-oa-sws#807]
I was testing the additional classrooms feature, and I think the selection was a little confusing.

2 classes (to my understanding), implies that it is Auxiliary classroom 1 and Auxiliary classroom 2. Suggestion: Main hall could be considered as a "default" option and not appear on the list.

Example:

Change options. Title: Class count?
Choice: Yes
             No

Thus, it implies that if "Yes", Auxiliary classroom 1 will be used. If "No" only Main hall will be used.

Or else:

Title: Class count?
Choice: Yes, Auxiliary classroom 1
             No, just the main hall

**Comment by rhahao** [comment]
Thanks for the feedback. May be we will change the label as Auxiliary Classroom, and the choice would be Yes and No.

**Comment by joaochris** [comment]
> Thanks for the feedback. May be we will change the label as Auxiliary Classroom, and the choice would be Yes and No.

That way it gets even better! 😉
