### ISSUE TITLE
[Enhancement] Option to not abbreviate in display name

### ISSUE THREAD

**Issue by joaochris** [sws2apps/lmm-oa-sws#829]
In my view this option could be an option of choice. Whether we want to abbreviate the names or not. In my case, I prefer not to abbreviate :).

**Comment by rhahao** [comment]
Hello @joaochris, yeah sure! It has been requested also from some users, so I will add this to the backlog list.

**Comment by joaochris** [comment]
@rhahao I am good and you?

Yeah, I don't think it's cool that way.

So in this case, you will need to work with the font size. Perhaps testing on behalf of the participants?
Or in the source material itself?

**Comment by rhahao** [comment]
I’m doing fine too, thanks! 👌

> So in this case, you will need to work with the font size. Perhaps testing on behalf of the participants?
Or in the source material itself?

I will try decreasing the font size for the participants first then. Do you think it is a better that the app can just trim the name if it is very long and cannot be fitted on one line?

**Comment by joaochris** [comment]
Yes! It's a great option :)

**Comment by rhahao** [comment]
How about this one now?

![schedule_fullname](https://user-images.githubusercontent.com/26148770/220391195-96f7b2c9-e230-4eee-998a-696927ab9fce.png)

**Comment by joaochris** [comment]
I think it turned out good :)

**Comment by joaochris** [comment]
If I say that it was weird with the spaces I would be being too annoying 😂

**Comment by rhahao** [comment]
I think that’s must be the side effect of it being spread out into 2 lines. Unless we think something very different from the S-140 template, I will release it like this for now. 😁 Hopefully, the light will get brighter and brighter in the future.
