### ISSUE TITLE
[Enhancement] Adjustments on the S-140

### ISSUE THREAD

**Issue by joaochris** [sws2apps/lmm-oa-sws#830]
Is it possible to make an adjustment so that the text is only on one line and not on two?

![Screenshot_13](https://user-images.githubusercontent.com/76891864/219058656-35f9689d-968f-464a-8867-7edb9c9d68d2.png)

**Comment by rhahao** [comment]
Hi @joaochris, thanks for your comment. I need to think about it. For example, what do you recommend in this case?

**Comment by rhahao** [comment]
That could be an idea. For example, in Malagasy language, we have always very long word. 🤣So I need to test that if it does not break something else. But anyway, we could add an option to decrease or increase the font size, and allow the user to change it according to their needs.

**Comment by rhahao** [comment]
On this one @joaochris, just to confirm: is it for every part in the S-140, or only for the Apply for Field Ministry part?

**Comment by joaochris** [comment]
Maybe it's better all over the S-140, so as not to be disproportionate and maintain a standard?

**Comment by joaochris** [comment]
Now that I've noticed. When you reduce the font, the text is misaligned with the ball. In that case, if you can't get aligned or if you find another alternative to reduce the font, you can close this problem. Also, you run the risk of getting too small in print.

**Comment by rhahao** [comment]
Yeah, you’re right! I’ll try to find what could be done.

**Comment by joaochris** [comment]
This one can also be closed, right? Since this one was also related? #829

**Comment by rhahao** [comment]
Yeah you’re right! 👍
