### ISSUE TITLE
[FIX] Invalid date error

### ISSUE THREAD

**Issue by joaochris** [sws2apps/lmm-oa-sws#831]
🤔
![Screenshot_18](https://user-images.githubusercontent.com/76891864/219070745-4612a179-0f85-4060-ae3b-22ce32e2a41b.png)

**Comment by rhahao** [comment]
When does this happens?

**Comment by joaochris** [comment]
I had the browser open in the background and when I clicked this appeared. If I reload this error appears again.

**Comment by joaochris** [comment]
Should I clear browser history completely?

**Comment by rhahao** [comment]
Hum... may be somehow related to the new whats new content that was published... Anyway, on my side, I checked even with your language, it works just fine. But I will check it asap where an invalid date could occur. If you delete the browser history, it will delete all your data as well. So not sure, if I should I recommend that.

**Comment by joaochris** [comment]
![image](https://user-images.githubusercontent.com/76891864/219073638-774270a6-52ca-42e3-bee1-930717eaa5ab.png)

**Comment by rhahao** [comment]
I think I’ve found something that I could improve to catch the exception. Not knowing yet why it behaves differently on your side. Update should be ready after few minutes. Apologies for the inconvenience. 😊

**Comment by joaochris** [comment]
All good! No problem :)

**Comment by joaochris** [comment]
Sorted out! You always hit the target! I had to hit update fast 😂

There was even a notification, but it disappeared when I clicked on it. Maybe it's bugged, but after starting later I'll see if the notification appears.

**Comment by rhahao** [comment]
Yeah, they are removed as soon as the next fetch was occurred. But it is on its way again. Sadly, I removed the one that makes it wait one hour again before appearing. But please, I am waiting for your feedback to know if it was solved on your side.

**Comment by joaochris** [comment]
All very well!
![Screenshot_19](https://user-images.githubusercontent.com/76891864/219129935-1a3a4c6a-e64c-4edd-a613-5c9a3a099343.png)
