### ISSUE TITLE
[FEAT] Option Keep me logged in

### ISSUE THREAD

**Issue by joaochris** [sws2apps/lmm-oa-sws#843]

**Comment by rhahao** [comment]
Hi @joaochris, may I please ask additional info about this one? Thanks.

**Comment by joaochris** [comment]
Clear :). When we haven't logged in for a while, we need to log in again. This process gets repetitive. It would be much better if it could save our session with the option to keep logged in, and then we will always log in without having to log in.

**Comment by rhahao** [comment]
Ah... now I understand. 😁 I will try to find a way on how to improve that. Currently, the session is only active for 1 day.
